### PR TITLE
Fix Supernova effect

### LINKED ISSUE #510: Bug: Supernova effect dies
## Bug report

**Problem**

The Supernova effect dies after a few runs/minutes, leaving a permanently black panel. The reason is that the number of elements/debris items seems to gradually decrease to 0.

**Steps**
1. Start the Supernova effect and let it run for a while, restarting it if necessary. 

**Notes**

Without being able to exactly pinpoint it, my guess would be that this behavior got introduced with the merge of #489.

### PR DESCRIPTION
**Pull request by rbergen**
## Description

This fixes #510. The main change is that the effect makes a clean start every run, as it used to before #489 was merged. I've also:

- Cleaned up a few (more) things that didn't seem to serve any purpose.
- Reinstated the use of `g()->isValidPixel()` to check if we're using sane x and y values, and skipping the draw otherwise.
- Added a check that only avoids sampling VU meter pixels if we're actually showing it.

## Contributing requirements

* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

File: include/effects/matrix/PatternSMSupernova.h [hunk 1]
```diff
@@ -112,6 +108,8 @@ class PatternSMSupernova : public LEDStripEffect
         if (debris_item._state == 0 || x < 0 || x >= MATRIX_WIDTH ||
```
Comment (davepl) [inline include/effects/matrix/PatternSMSupernova.h:108]: Good opportunity to reflow this line!

File: include/effects/matrix/PatternSMSupernova.h [hunk 2]
```diff
@@ -137,17 +135,23 @@ class PatternSMSupernova : public LEDStripEffect
...
-            // but we just clamp instead.
-            const int xn = std::clamp((int)x + (i & 1), 0, MATRIX_WIDTH - 1);
-            const int yn = std::clamp((int)y + ((i >> 1) & 1), 0, MATRIX_HEIGHT - 1);
-
-            CRGB clr = g()->leds[XY(xn, MATRIX_HEIGHT - yn)];
+            const int xn = x + (i & 1);
+            const int yn = y + ((i >> 1) & 1);
+
+            // Make sure we're on the panel and leave the VU meter pixels alone, if we're showing it
+            if (!g()->isValidPixel(xn, yn) || (showingVUMeter && yn == (MATRIX_HEIGHT - 1)))
```
Comment (davepl) [inline include/effects/matrix/PatternSMSupernova.h:151]: Why the extra level of labels?  Why not (SHOW_VU_METER) directly in the expression, since it will always be defined?

File: include/effects/matrix/PatternSMSupernova.h [hunk 3]
```diff
@@ -24,10 +24,8 @@ class PatternSMSupernova : public LEDStripEffect
 
     void Start() override
     {
+        std::for_each(_debris_items.begin(), _debris_items.end(), [](DebrisItem& debris_item) { debris_item.Clear(); });
         g()->Clear();
-        enlargedDebrisItemNUM = 200;
-        if (enlargedDebrisItemNUM > MAX_COUNT)
-            enlargedDebrisItemNUM = 200U;
```
Comment (davepl) [inline include/effects/matrix/PatternSMSupernova.h:30]: Is this the same 200 as the debris count define below?  I don't think they're liinked?

File: include/effects/matrix/PatternSMSupernova.h (hunk 1 above)
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h:108]: I actually didn't touch this in past because I'm not sure how to restructure it in a way to make it better. It's a whole bunch of terms no matter how you slice and dice it.  
I'm happy to take on a concrete proposal though! :)

File: include/effects/matrix/PatternSMSupernova.h (hunk 2 above)
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h:151]: It actually isn't always defined. It's only defined for matrix/HUB75 configurations, and even then not for all - env:mesmerizer_lolin doesn't, as I found when CI ran on an earlier commit. However, @robertlipe made a good alternative suggestion, which I will implement.

File: include/effects/matrix/PatternSMSupernova.h (hunk 3 above)
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h:30]: I didn't change the debris count magic to something I came up with myself. I reverted to the value it had before #489. At that time there was an index "if" that ran up to the value of `enlargedDebrisItemNUM`, thus 200.

File: include/effects/matrix/PatternSMSupernova.h [hunk 4]
```diff
@@ -24,10 +24,8 @@ class PatternSMSupernova : public LEDStripEffect
 
     void Start() override
     {
+        std::for_each(_debris_items.begin(), _debris_items.end(), [](DebrisItem& debris_item) { debris_item.Clear(); });
```
[the remark this answers is not in the document]
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h:27]: No, the thing is that the original (pre-#489) logic started with a zeroed out set of arrays (now array of `DebrisItem` objects) every time the effect was started. I figured that was an important factor in the effect working correctly, as it "eats" its own output of `Draw()`, the next time `Draw()` is called. The `DebrisItem` constructor would only be called once per `DebrisItem` when the effect itself was created, now the `DebrisItem` objects are also cleared on every invocation of `Start()`.

File: include/effects/matrix/PatternSMSupernova.h [hunk 5]
```diff
@@ -137,17 +135,23 @@ class PatternSMSupernova : public LEDStripEffect
 
     void drawPixelXYF(float x, float y, CRGB color)
     {
+        #if SHOW_VU_METER
```
[the remark this answers is not in the document]
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h:138]: I was looking for that thing, but couldn't find it. After looking again, now I have `¯\_(ツ)_/¯`. It's `EffectManager::IsVUVisible()`. Which I will promptly employ instead.

File: include/effects/matrix/PatternSMSupernova.h (hunk 1 above)
Comment (rbergen) [reply include/effects/matrix/PatternSMSupernova.h]: Had another look and came up with an idea after all. Thanks for the tickle! :)
